[package]
name = "kalosm-common"
version = "0.3.3"
edition = "2021"
description = "Helpers for kalosm downloads and candle utilities"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candle-core.workspace = true
candle-nn.workspace = true
hf-hub = { version = "0.3.0" }
reqwest = "0.11.24"
tokio = { version = "1.36.0", features = ["full"] }
dirs = "5.0.1"
tracing = "0.1.40"
httpdate = "1.0.3"
indicatif = "0.17.8"
metal = { version = "0.29.0", optional = true }
once_cell = "1.19.0"
thiserror.workspace = true

[features]
metal = ["dep:metal"]
