[package]
name = "kalosm-llama"
version = "0.3.3"
edition = "2021"
description = "A simple interface for Llama models "
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff"]
keywords = ["llm", "llama", "mistral", "agents", "nlp"]

[dependencies]
candle-core.workspace = true
candle-nn.workspace = true
candle-transformers.workspace = true
tokenizers = { version = "0.19.1" }

accelerate-src = { version = "0.3.2", optional = true }
intel-mkl-src = { version = "0.8.1", features = ["mkl-static-lp64-iomp"], optional = true }
cudarc = { version = "0.9.14", features = ["f16"], optional = true }
half = { version = "2.3.1" }

tracing = "0.1.37"
rand = "0.8.5"
tokio = { version = "1.32.0", features = ["full"] }
async-trait = "0.1.73"
once_cell = "1.19.0"
rayon = { version = "1.8.0", optional = true }
llm-samplers.workspace = true
kalosm-sample.workspace = true
kalosm-language-model.workspace = true
kalosm-streams.workspace = true
kalosm-common = { workspace = true }
thiserror.workspace = true

[dev-dependencies]
tracing-subscriber = "0.3.18"
criterion = "0.5.1"
kalosm = { path = "../../interfaces/kalosm", features = ["language"] }

[features]
default = []
accelerate = ["dep:accelerate-src", "candle-core/accelerate", "candle-nn/accelerate", "candle-transformers/accelerate"]
cuda = ["candle-core/cuda", "candle-nn/cuda", "candle-transformers/cuda"]
cudnn = ["candle-core/cudnn"]
mkl = ["dep:intel-mkl-src", "candle-core/mkl", "candle-nn/mkl", "candle-transformers/mkl"]
nccl = ["cuda", "cudarc/nccl", "half/num-traits", "half/use-intrinsics", "half/rand_distr"]
metal = ["candle-core/metal", "candle-nn/metal", "candle-transformers/metal", "kalosm-common/metal"]
rayon = ["dep:rayon"]

[[bench]]
name = "inferance"
harness = false
