[package]
name = "kalosm-learning"
version = "0.3.3"
edition = "2021"
description = "A simplified machine learning library for building off of pretrained models."
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff"]
keywords = ["ai", "bert", "nlp", "machine-learning", "transformers"]

[dependencies]
kalosm-language-model.workspace = true
kalosm-learning-macro.workspace = true
candle-core.workspace = true
candle-nn.workspace = true
tokio-util = { version = "0.7.9", features = ["rt"] }
half = "2.3.1"
rand = "0.8.5"
tokio = { version = "1.34.0", features = ["full"] }
kalosm-common.workspace = true

[dev-dependencies]
rbert.workspace = true

[features]
metal = ["candle-core/metal", "candle-nn/metal", "kalosm-common/metal"]
